{
 "title": "Daily Summaries",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  { "title": "Apple Activity Rings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "When did I meet my Move goals?",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cal" } },
   "targets": [
    {
     "rawSql": "SELECT\n  summary_date AS \"time\",\n  active_energy_burned as \"Active Energy Burned\",\n  active_energy_burned_goal as \"Goal\"\nFROM hk_activity_summary\nWHERE\n  $__timeFilter(summary_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "How often do I meet my move goal?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  goal_met_days as \"Met Goal\",\n  total_days as \"Total Days\",\n  goal_met_days / total_days as \"Achievment Rate\"\nFROM (\n  SELECT\n    count(summary_date) as goal_met_days,\n    DATE_PART('day', \n                 to_timestamp('${__to:date:seconds}')  - \n                 to_timestamp('${__from:date:seconds}')\n      ) as total_days\n  FROM\n    hk_activity_summary\n  WHERE\n    $__timeFilter(summary_date)\n  AND\n    active_energy_burned >= active_energy_burned_goal\n  ORDER BY 1\n) n1"
    }
   ]
  },
  {
   "title": "Do I meet my Exercise goals?",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "min" } },
   "targets": [
    {
     "rawSql": "SELECT\n  summary_date AS \"time\",\n  apple_exercise_time as \"Exercise Time\",\n  apple_exercise_time_goal as \"Goal\"\nFROM hk_activity_summary\nWHERE\n  $__timeFilter(summary_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "How often do I meet my exercise goal?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  goal_met_days as \"Met Goal\",\n  total_days as \"Total Days\",\n  goal_met_days / total_days as \"Achievment Rate\"\nFROM (\n  SELECT\n    count(summary_date) as goal_met_days,\n    DATE_PART('day', \n                 to_timestamp('${__to:date:seconds}')  - \n                 to_timestamp('${__from:date:seconds}')\n      ) as total_days\n  FROM\n    hk_activity_summary\n  WHERE\n    $__timeFilter(summary_date)\n  AND\n    apple_exercise_time >= apple_exercise_time_goal\n  ORDER BY 1\n) n1"
    }
   ]
  },
  {
   "title": "Do I meet my Stand goals?",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hrs" } },
   "targets": [
    {
     "rawSql": "SELECT\n  summary_date AS \"time\",\n  apple_stand_hours as \"Stand Hours\",\n  apple_stand_hours_goal as \"Goal\"\nFROM hk_activity_summary\nWHERE\n  $__timeFilter(summary_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "How often do I meet my stand goal?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  goal_met_days as \"Met Goal\",\n  total_days as \"Total Days\",\n  goal_met_days / total_days as \"Achievment Rate\"\nFROM (\n  SELECT\n    count(summary_date) as goal_met_days,\n    DATE_PART('day', \n                 to_timestamp('${__to:date:seconds}')  - \n                 to_timestamp('${__from:date:seconds}')\n      ) as total_days\n  FROM\n    hk_activity_summary\n  WHERE\n    $__timeFilter(summary_date)\n  AND\n    apple_stand_hours >= apple_stand_hours_goal\n  ORDER BY 1\n) n1"
    }
   ]
  },
  {
   "title": "How often do I close all my rings?",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  --to_char(summary_date, 'Day') AS \"day\",\n  summary_date as \"time\",\n  -- 1 as \"All Goals Met\"\n  to_char(summary_date, 'Day') AS \"All Goals Met\"\nFROM hk_activity_summary\nWHERE\n  $__timeFilter(summary_date)\nAND\n  active_energy_burned >= active_energy_burned_goal\nAND\n  apple_exercise_time >= apple_exercise_time_goal\nAND \n  apple_stand_hours >= apple_stand_hours_goal\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  --to_char(summary_date, 'Day') AS \"day\",\n  summary_date as \"time\",\n  -- 1 as \"All Goals Met\"\n  to_char(summary_date, 'Day') AS \"Goals Not Met\"\nFROM hk_activity_summary\nWHERE\n  $__timeFilter(summary_date)\nAND (\n  active_energy_burned < active_energy_burned_goal\n  OR\n  apple_exercise_time < apple_exercise_time_goal\n  OR \n  apple_stand_hours < apple_stand_hours_goal\n)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "How often do I meet all my goals?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  goal_met_days as \"Met Goal\",\n  total_days as \"Total Days\",\n  goal_met_days / total_days as \"Achievment Rate\"\nFROM (\n  SELECT\n    count(summary_date) as goal_met_days,\n    DATE_PART('day', \n                 to_timestamp('${__to:date:seconds}')  - \n                 to_timestamp('${__from:date:seconds}')\n      ) as total_days\n  FROM\n    hk_activity_summary\n  WHERE\n    $__timeFilter(summary_date)\n  AND\n    active_energy_burned >= active_energy_burned_goal\n  AND\n    apple_exercise_time >= apple_exercise_time_goal\n  AND \n    apple_stand_hours >= apple_stand_hours_goal\n  ORDER BY 1\n) n1"
    }
   ]
  },
  { "title": "What is the average daily...", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Body Mass\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'BodyMass'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Lean Body Mass\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'LeanBodyMass'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Body Fat %\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'BodyFatPercentage'\nORDER BY time"
    }
   ]
  },
  {
   "title": "...time spent in bed?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n  creation_date::date as time,\n  sum(EXTRACT(EPOCH FROM (end_date - start_date))) as \"Time in Bed\"\nfrom hk_category_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKCategoryTypeIdentifierSleepAnalysis'\nAND \n  hk_value = 'HKCategoryValueSleepAnalysisInBed'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...time spent exercising?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Exercise Time\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'AppleExerciseTime'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...calories burned?",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Resting\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'BasalEnergyBurned'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Active\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'ActiveEnergyBurned'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...steps taken?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n  creation_date::date as time,\n  sum(hk_value) as \"Steps\"\nfrom hk_quantity_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'StepCount'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...flights of stairs climbed?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n  creation_date::date as time,\n  sum(hk_value) as \"Flights Climbed\"\nfrom hk_quantity_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'FlightsClimbed'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...distance run / walked?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n  creation_date::date as time,\n  sum(hk_value) as \"Distance\"\nfrom hk_quantity_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'DistanceWalkingRunning'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...time spent standing?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Stand Time\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'AppleStandTime'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "... stand hours per day?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroupAlias(start_date, '1d', 0),\n  count(hk_value) as \"# of Hour Stood 1 min\"\nfrom hk_category_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKCategoryTypeIdentifierAppleStandHour'\nAND\n  hk_value = 'HKCategoryValueAppleStandHourStood'\nGROUP BY time\nORDER BY time"
    }
   ]
  }
 ]
}