{
 "title": "Health Kit",
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "SELECT distinct(hk_source)\nFROM hk_quantity_record\nUNION\nSELECT distinct(hk_source)\nFROM hk_category_record\nORDER BY hk_source"
   }
  ]
 },
 "panels": [
  {
   "title": "What is the average daily amount of...",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "How much do I weigh?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Body Mass\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierBodyMass'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Lean Body Mass\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierLeanBodyMass'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Body Fat %\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierBodyFatPercentage'\nORDER BY time"
    }
   ]
  },
  {
   "title": "...time spent in bed?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n  creation_date::date as time,\n  sum(EXTRACT(EPOCH FROM (end_date - start_date))) as \"Time in Bed\"\nfrom hk_category_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKCategoryTypeIdentifierSleepAnalysis'\nAND \n  hk_value = 'HKCategoryValueSleepAnalysisInBed'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...time spent exercising?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Exercise Time\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierAppleExerciseTime'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...calories burned?",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Resting\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierBasalEnergyBurned'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Active\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierActiveEnergyBurned'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...steps taken?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n  creation_date::date as time,\n  sum(hk_value) as \"Steps\"\nfrom hk_quantity_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierStepCount'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...flights of stairs climbed?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n  creation_date::date as time,\n  sum(hk_value) as \"Flights Climbed\"\nfrom hk_quantity_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierFlightsClimbed'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...distance run / walked?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n  creation_date::date as time,\n  sum(hk_value) as \"Distance\"\nfrom hk_quantity_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierDistanceWalkingRunning'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "...time spent standing?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Stand Time\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierAppleStandTime'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "... stand hours per day?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroupAlias(start_date, '1d', 0),\n  count(hk_value) as \"# of Hour Stood 1 min\"\nfrom hk_category_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKCategoryTypeIdentifierAppleStandHour'\nAND\n  hk_value = 'HKCategoryValueAppleStandHourStood'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "How much time do I spend in bed each day?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select\n  creation_date::date as time,\n  sum(EXTRACT(EPOCH FROM (end_date - start_date))) as \"Time in Bed\"\nfrom hk_category_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKCategoryTypeIdentifierSleepAnalysis'\nAND \n  hk_value = 'HKCategoryValueSleepAnalysisInBed'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "How much time do I spend standing each day?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Stand Time\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierAppleStandTime'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "How much time do I spend exercising each day?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Exercise Time\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierAppleExerciseTime'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "How many calories do I use per day?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Resting\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierBasalEnergyBurned'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', NULL),\n  sum(hk_value) as \"Active\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierActiveEnergyBurned'\nAND\n  hk_source = 'Nathaniel’s Apple Watch'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "How many steps per day were taken?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', 0),\n  sum(hk_value) as \"Steps Per Day\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierStepCount'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "How many flights of stairs were climbed per day?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', 0),\n  sum(hk_value) as \"Flights Climbed per Day\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierFlightsClimbed'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "How far do I walk/run each day?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_date, '1d', 0),\n  sum(hk_value) as \"Miles per Day\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierDistanceWalkingRunning'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "How many stand hours do I have per day?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroupAlias(start_date, '1d', 0),\n  count(hk_value) as \"# of Hour Stood 1 min\"\nfrom hk_category_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKCategoryTypeIdentifierAppleStandHour'\nAND\n  hk_value = 'HKCategoryValueAppleStandHourStood'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  { "title": "Body Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "How much do I weigh?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "yaxes": [
    { "format": "masslb" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Body Mass\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierBodyMass'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Lean Body Mass\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierLeanBodyMass'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Body Fat %\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierBodyFatPercentage'\nORDER BY time"
    }
   ]
  },
  {
   "title": "What is my BMI?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"BMI\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierBodyMassIndex'\nORDER BY time"
    }
   ]
  },
  { "title": "Vital Signs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "What is my daily heart rate?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "BPM" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', start_date AT TIME ZONE 'MDT') as time,\n  min(hk_value),\n  avg(hk_value),\n  max(hk_value)\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierHeartRate'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "What is my O2 Saturation?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', start_date AT TIME ZONE 'MDT') as time,\n  min(hk_value),\n  avg(hk_value),\n  max(hk_value)\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierOxygenSaturation'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "What are my average resting and walking heart rates?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Resting\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierRestingHeartRate'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Walking\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierWalkingHeartRateAverage'\nORDER BY time"
    }
   ]
  },
  {
   "title": "What is my heart rate variability?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', start_date AT TIME ZONE 'MDT') as time,\n  min(hk_value),\n  avg(hk_value),\n  max(hk_value)\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierHeartRateVariabilitySDNN'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  { "title": "Mobility", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "How fast do I walk?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Walking Speed\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierWalkingSpeed'\nORDER BY time"
    }
   ]
  },
  {
   "title": "What is my step length?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Step Length\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierWalkingStepLength'\nORDER BY time"
    }
   ]
  },
  {
   "title": "What is my walking asymmetry percentage?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Walking Asymmetry\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierWalkingAsymmetryPercentage'\nORDER BY time"
    }
   ]
  },
  {
   "title": "What is my walking double support percentage?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Walking Double Support\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage'\nORDER BY time"
    }
   ]
  },
  {
   "title": "How fast do I travel on stairs?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ft/s" } },
   "yaxes": [
    { "format": "ft/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Descent\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierStairDescentSpeed'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  start_date as time,\n  hk_value as \"Ascent\"\nFROM \n  public.hk_quantity_record\nWHERE\n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKQuantityTypeIdentifierStairAscentSpeed'\nORDER BY time"
    }
   ]
  },
  {
   "title": "When did I stand?",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroupAlias(start_date, '1h', -1),\n  CASE\n    WHEN hk_value = 'HKCategoryValueAppleStandHourStood' THEN 1\n    WHEN hk_value = 'HKCategoryValueAppleStandHourIdle' THEN 0\n  END as \"Standing Status\"\nfrom hk_category_record \nwhere \n  $__timeFilter(start_date)\nAND\n  hk_type = 'HKCategoryTypeIdentifierAppleStandHour'\nORDER BY time"
    }
   ]
  }
 ]
}